language: generic
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
env:
  global:
    - FLUTTER_CHANNEL=stable
install:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH="$PATH:`pwd`/flutter/bin/cache/dart-sdk/bin"
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor -v
  - flutter packages get

static_analysis: &static_analysis
  name: "Static analysis"
  script: flutter analyze --no-current-package $TRAVIS_BUILD_DIR/lib

jobs:
  allow_failures:
    - env: FLUTTER_CHANNEL=beta
  include:
    - <<: *static_analysis
    - stage: build
    - stage: deploy
